# Generated by Django 5.0.7 on 2024-08-08 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versiculo',
            old_name='citacao',
            new_name='texto',
        ),
    ]
