# Generated by Django 5.0.7 on 2024-08-08 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_citacao_versiculo_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='igreja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.igreja'),
        ),
    ]
