# Generated by Django 5.0.7 on 2024-08-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pessoa_ativo_pessoa_igreja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='corpo',
            new_name='texto',
        ),
    ]
