# Generated by Django 5.0.7 on 2024-08-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_pessoa_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoaovivo',
            name='link_youtube',
            field=models.CharField(),
        ),
    ]
