# Generated by Django 5.0.7 on 2024-08-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_eventoaovivo_link_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='material_externo',
            field=models.CharField(blank=True, null=True),
        ),
    ]
