# Generated by Django 5.0.7 on 2024-08-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_noticia_material_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorianoticia',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
