# Generated by Django 5.0.7 on 2024-08-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_evento_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoaovivo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
