# Generated by Django 5.0.7 on 2024-08-31 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_categoriaagenda_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='imagem',
        ),
    ]
