version: '3'

services:
  backend:
    build: 
      context: ./backend
    command: gunicorn backend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: 
      context: ./frontend
    volumes:
      - react_build:/react/build

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - react_build:/var/www/react
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=.9KGE*2*AKywLttqagu*
      - POSTGRES_DB=db_igreja_online
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data


volumes:
  react_build: