export const CATEGORIA_LIST_REQUEST = 'CATEGORIA_LIST_REQUEST';
export const CATEGORIA_LIST_SUCCESS = 'CATEGORIA_LIST_SUCCESS';
export const CATEGORIA_LIST_FAIL = 'CATEGORIA_LIST_FAIL';

export const CATEGORIA_DELETE_REQUEST = 'CATEGORIA_DELETE_REQUEST';
export const CATEGORIA_DELETE_SUCCESS = 'CATEGORIA_DELETE_SUCCESS';
export const CATEGORIA_DELETE_FAIL = 'CATEGORIA_DELETE_FAIL';
