export const CATEGORIA_LIST_REQUEST = 'CATEGORIA_LIST_REQUEST';
export const CATEGORIA_LIST_SUCCESS = 'CATEGORIA_LIST_SUCCESS';
export const CATEGORIA_LIST_FAIL = 'CATEGORIA_LIST_FAIL';

export const CATEGORIA_DELETE_REQUEST = 'CATEGORIA_DELETE_REQUEST';
export const CATEGORIA_DELETE_SUCCESS = 'CATEGORIA_DELETE_SUCCESS';
export const CATEGORIA_DELETE_FAIL = 'CATEGORIA_DELETE_FAIL';

export const CATEGORIA_DETAILS_REQUEST = 'CATEGORIA_DETAILS_REQUEST';
export const CATEGORIA_DETAILS_SUCCESS = 'CATEGORIA_DETAILS_SUCCESS';
export const CATEGORIA_DETAILS_FAIL = 'CATEGORIA_DETAILS_FAIL';

export const CATEGORIA_UPDATE_REQUEST = 'CATEGORIA_UPDATE_REQUEST';
export const CATEGORIA_UPDATE_SUCCESS = 'CATEGORIA_UPDATE_SUCCESS';
export const CATEGORIA_UPDATE_FAIL = 'CATEGORIA_UPDATE_FAIL';
export const CATEGORIA_UPDATE_RESET = 'CATEGORIA_UPDATE_RESET';

export const CATEGORIA_CREATE_REQUEST = 'CATEGORIA_CREATE_REQUEST';
export const CATEGORIA_CREATE_SUCCESS = 'CATEGORIA_CREATE_SUCCESS';
export const CATEGORIA_CREATE_FAIL = 'CATEGORIA_CREATE_FAIL';
export const CATEGORIA_CREATE_RESET = 'CATEGORIA_CREATE_RESET';