export const ENDERECO_LIST_REQUEST = 'ENDERECO_LIST_REQUEST';
export const ENDERECO_LIST_SUCCESS = 'ENDERECO_LIST_SUCCESS';
export const ENDERECO_LIST_FAIL = 'ENDERECO_LIST_FAIL';

export const ENDERECO_DELETE_REQUEST = 'ENDERECO_DELETE_REQUEST';
export const ENDERECO_DELETE_SUCCESS = 'ENDERECO_DELETE_SUCCESS';
export const ENDERECO_DELETE_FAIL = 'ENDERECO_DELETE_FAIL';
