export const ENDERECO_LIST_REQUEST = 'ENDERECO_LIST_REQUEST';
export const ENDERECO_LIST_SUCCESS = 'ENDERECO_LIST_SUCCESS';
export const ENDERECO_LIST_FAIL = 'ENDERECO_LIST_FAIL';

export const ENDERECO_DELETE_REQUEST = 'ENDERECO_DELETE_REQUEST';
export const ENDERECO_DELETE_SUCCESS = 'ENDERECO_DELETE_SUCCESS';
export const ENDERECO_DELETE_FAIL = 'ENDERECO_DELETE_FAIL';

export const ENDERECO_DETAILS_REQUEST = 'ENDERECO_DETAILS_REQUEST';
export const ENDERECO_DETAILS_SUCCESS = 'ENDERECO_DETAILS_SUCCESS';
export const ENDERECO_DETAILS_FAIL = 'ENDERECO_DETAILS_FAIL';

export const ENDERECO_UPDATE_REQUEST = 'ENDERECO_UPDATE_REQUEST';
export const ENDERECO_UPDATE_SUCCESS = 'ENDERECO_UPDATE_SUCCESS';
export const ENDERECO_UPDATE_FAIL = 'ENDERECO_UPDATE_FAIL';
export const ENDERECO_UPDATE_RESET = 'ENDERECO_UPDATE_RESET';

export const ENDERECO_CREATE_REQUEST = 'ENDERECO_CREATE_REQUEST';
export const ENDERECO_CREATE_SUCCESS = 'ENDERECO_CREATE_SUCCESS';
export const ENDERECO_CREATE_FAIL = 'ENDERECO_CREATE_FAIL';
export const ENDERECO_CREATE_RESET = 'ENDERECO_CREATE_RESET';
