export const ESTADO_CIVIL_LIST_REQUEST = 'ESTADO_CIVIL_LIST_REQUEST';
export const ESTADO_CIVIL_LIST_SUCCESS = 'ESTADO_CIVIL_LIST_SUCCESS';
export const ESTADO_CIVIL_LIST_FAIL = 'ESTADO_CIVIL_LIST_FAIL';

export const ESTADO_CIVIL_DELETE_REQUEST = 'ESTADO_CIVIL_DELETE_REQUEST';
export const ESTADO_CIVIL_DELETE_SUCCESS = 'ESTADO_CIVIL_DELETE_SUCCESS';
export const ESTADO_CIVIL_DELETE_FAIL = 'ESTADO_CIVIL_DELETE_FAIL';
