export const GENERO_LIST_REQUEST = 'GENERO_LIST_REQUEST';
export const GENERO_LIST_SUCCESS = 'GENERO_LIST_SUCCESS';
export const GENERO_LIST_FAIL = 'GENERO_LIST_FAIL';

export const GENERO_DELETE_REQUEST = 'GENERO_DELETE_REQUEST';
export const GENERO_DELETE_SUCCESS = 'GENERO_DELETE_SUCCESS';
export const GENERO_DELETE_FAIL = 'GENERO_DELETE_FAIL';
