export const IGREJA_LIST_REQUEST = 'IGREJA_LIST_REQUEST';
export const IGREJA_LIST_SUCCESS = 'IGREJA_LIST_SUCCESS';
export const IGREJA_LIST_FAIL = 'IGREJA_LIST_FAIL';

export const IGREJA_DELETE_REQUEST = 'IGREJA_DELETE_REQUEST';
export const IGREJA_DELETE_SUCCESS = 'IGREJA_DELETE_SUCCESS';
export const IGREJA_DELETE_FAIL = 'IGREJA_DELETE_FAIL';
