export const PESSOA_LIST_REQUEST = 'PESSOA_LIST_REQUEST';
export const PESSOA_LIST_SUCCESS = 'PESSOA_LIST_SUCCESS';
export const PESSOA_LIST_FAIL = 'PESSOA_LIST_FAIL';

export const PESSOA_DELETE_REQUEST = 'PESSOA_DELETE_REQUEST';
export const PESSOA_DELETE_SUCCESS = 'PESSOA_DELETE_SUCCESS';
export const PESSOA_DELETE_FAIL = 'PESSOA_DELETE_FAIL';
