export const PROFISSAO_LIST_REQUEST = 'PROFISSAO_LIST_REQUEST';
export const PROFISSAO_LIST_SUCCESS = 'PROFISSAO_LIST_SUCCESS';
export const PROFISSAO_LIST_FAIL = 'PROFISSAO_LIST_FAIL';

export const PROFISSAO_DELETE_REQUEST = 'PROFISSAO_DELETE_REQUEST';
export const PROFISSAO_DELETE_SUCCESS = 'PROFISSAO_DELETE_SUCCESS';
export const PROFISSAO_DELETE_FAIL = 'PROFISSAO_DELETE_FAIL';
