# Generated by Django 4.2.4 on 2023-08-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja_online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='observacao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
