# Generated by Django 4.2.4 on 2023-09-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igreja_online', '0003_pessoa_bairro_pessoa_cep_pessoa_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='igreja',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='igreja',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='igreja',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='igreja',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='igreja',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='igreja',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='igreja',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
