export const AGENDA_LIST_REQUEST = "AGENDA_LIST_REQUEST";
export const AGENDA_LIST_SUCCESS = "AGENDA_LIST_SUCCESS";
export const AGENDA_LIST_FAIL = "AGENDA_LIST_FAIL";

export const AGENDA_DETAILS_REQUEST = "AGENDA_DETAILS_REQUEST";
export const AGENDA_DETAILS_SUCCESS = "AGENDA_DETAILS_SUCCESS";
export const AGENDA_DETAILS_FAIL = "AGENDA_DETAILS_FAIL";

export const AGENDA_CREATE_REQUEST = "AGENDA_CREATE_REQUEST";
export const AGENDA_CREATE_SUCCESS = "AGENDA_CREATE_SUCCESS";
export const AGENDA_CREATE_FAIL = "AGENDA_CREATE_FAIL";
export const AGENDA_CREATE_RESET = "AGENDA_CREATE_RESET";

export const AGENDA_UPDATE_REQUEST = "AGENDA_UPDATE_REQUEST";
export const AGENDA_UPDATE_SUCCESS = "AGENDA_UPDATE_SUCCESS";
export const AGENDA_UPDATE_FAIL = "AGENDA_UPDATE_FAIL";
export const AGENDA_UPDATE_RESET = "AGENDA_UPDATE_RESET";

export const AGENDA_DELETE_REQUEST = "AGENDA_DELETE_REQUEST";
export const AGENDA_DELETE_SUCCESS = "AGENDA_DELETE_SUCCESS";
export const AGENDA_DELETE_FAIL = "AGENDA_DELETE_FAIL";
