export const CARROSSEL_IMAGEM_LIST_REQUEST = "CARROSSEL_IMAGEM_LIST_REQUEST";
export const CARROSSEL_IMAGEM_LIST_SUCCESS = "CARROSSEL_IMAGEM_LIST_SUCCESS";
export const CARROSSEL_IMAGEM_LIST_FAIL = "CARROSSEL_IMAGEM_LIST_FAIL";

export const CARROSSEL_IMAGEM_DETAILS_REQUEST = "CARROSSEL_IMAGEM_DETAILS_REQUEST";
export const CARROSSEL_IMAGEM_DETAILS_SUCCESS = "CARROSSEL_IMAGEM_DETAILS_SUCCESS";
export const CARROSSEL_IMAGEM_DETAILS_FAIL = "CARROSSEL_IMAGEM_DETAILS_FAIL";

export const CARROSSEL_IMAGEM_CREATE_REQUEST = "CARROSSEL_IMAGEM_CREATE_REQUEST";
export const CARROSSEL_IMAGEM_CREATE_SUCCESS = "CARROSSEL_IMAGEM_CREATE_SUCCESS";
export const CARROSSEL_IMAGEM_CREATE_FAIL = "CARROSSEL_IMAGEM_CREATE_FAIL";
export const CARROSSEL_IMAGEM_CREATE_RESET = "CARROSSEL_IMAGEM_CREATE_RESET";

export const CARROSSEL_IMAGEM_UPDATE_REQUEST = "CARROSSEL_IMAGEM_UPDATE_REQUEST";
export const CARROSSEL_IMAGEM_UPDATE_SUCCESS = "CARROSSEL_IMAGEM_UPDATE_SUCCESS";
export const CARROSSEL_IMAGEM_UPDATE_FAIL = "CARROSSEL_IMAGEM_UPDATE_FAIL";
export const CARROSSEL_IMAGEM_UPDATE_RESET = "CARROSSEL_IMAGEM_UPDATE_RESET";

export const CARROSSEL_IMAGEM_DELETE_REQUEST = "CARROSSEL_IMAGEM_DELETE_REQUEST";
export const CARROSSEL_IMAGEM_DELETE_SUCCESS = "CARROSSEL_IMAGEM_DELETE_SUCCESS";
export const CARROSSEL_IMAGEM_DELETE_FAIL = "CARROSSEL_IMAGEM_DELETE_FAIL";