export const CATEGORIA_NOTICIA_LIST_REQUEST = "CATEGORIA_NOTICIA_LIST_REQUEST";
export const CATEGORIA_NOTICIA_LIST_SUCCESS = "CATEGORIA_NOTICIA_LIST_SUCCESS";
export const CATEGORIA_NOTICIA_LIST_FAIL = "CATEGORIA_NOTICIA_LIST_FAIL";

export const CATEGORIA_NOTICIA_DETAILS_REQUEST = "CATEGORIA_NOTICIA_DETAILS_REQUEST";
export const CATEGORIA_NOTICIA_DETAILS_SUCCESS = "CATEGORIA_NOTICIA_DETAILS_SUCCESS";
export const CATEGORIA_NOTICIA_DETAILS_FAIL = "CATEGORIA_NOTICIA_DETAILS_FAIL";

export const CATEGORIA_NOTICIA_CREATE_REQUEST = "CATEGORIA_NOTICIA_CREATE_REQUEST";
export const CATEGORIA_NOTICIA_CREATE_SUCCESS = "CATEGORIA_NOTICIA_CREATE_SUCCESS";
export const CATEGORIA_NOTICIA_CREATE_FAIL = "CATEGORIA_NOTICIA_CREATE_FAIL";
export const CATEGORIA_NOTICIA_CREATE_RESET = "CATEGORIA_NOTICIA_CREATE_RESET";

export const CATEGORIA_NOTICIA_UPDATE_REQUEST = "CATEGORIA_NOTICIA_UPDATE_REQUEST";
export const CATEGORIA_NOTICIA_UPDATE_SUCCESS = "CATEGORIA_NOTICIA_UPDATE_SUCCESS";
export const CATEGORIA_NOTICIA_UPDATE_FAIL = "CATEGORIA_NOTICIA_UPDATE_FAIL";
export const CATEGORIA_NOTICIA_UPDATE_RESET = "CATEGORIA_NOTICIA_UPDATE_RESET";

export const CATEGORIA_NOTICIA_DELETE_REQUEST = "CATEGORIA_NOTICIA_DELETE_REQUEST";
export const CATEGORIA_NOTICIA_DELETE_SUCCESS = "CATEGORIA_NOTICIA_DELETE_SUCCESS";
export const CATEGORIA_NOTICIA_DELETE_FAIL = "CATEGORIA_NOTICIA_DELETE_FAIL";