export const CATEGORIA_AGENDA_LIST_REQUEST = "CATEGORIA_AGENDA_LIST_REQUEST";
export const CATEGORIA_AGENDA_LIST_SUCCESS = "CATEGORIA_AGENDA_LIST_SUCCESS";
export const CATEGORIA_AGENDA_LIST_FAIL = "CATEGORIA_AGENDA_LIST_FAIL";

export const CATEGORIA_AGENDA_DETAILS_REQUEST = "CATEGORIA_AGENDA_DETAILS_REQUEST";
export const CATEGORIA_AGENDA_DETAILS_SUCCESS = "CATEGORIA_AGENDA_DETAILS_SUCCESS";
export const CATEGORIA_AGENDA_DETAILS_FAIL = "CATEGORIA_AGENDA_DETAILS_FAIL";

export const CATEGORIA_AGENDA_CREATE_REQUEST = "CATEGORIA_AGENDA_CREATE_REQUEST";
export const CATEGORIA_AGENDA_CREATE_SUCCESS = "CATEGORIA_AGENDA_CREATE_SUCCESS";
export const CATEGORIA_AGENDA_CREATE_FAIL = "CATEGORIA_AGENDA_CREATE_FAIL";
export const CATEGORIA_AGENDA_CREATE_RESET = "CATEGORIA_AGENDA_CREATE_RESET";

export const CATEGORIA_AGENDA_UPDATE_REQUEST = "CATEGORIA_AGENDA_UPDATE_REQUEST";
export const CATEGORIA_AGENDA_UPDATE_SUCCESS = "CATEGORIA_AGENDA_UPDATE_SUCCESS";
export const CATEGORIA_AGENDA_UPDATE_FAIL = "CATEGORIA_AGENDA_UPDATE_FAIL";
export const CATEGORIA_AGENDA_UPDATE_RESET = "CATEGORIA_AGENDA_UPDATE_RESET";

export const CATEGORIA_AGENDA_DELETE_REQUEST = "CATEGORIA_AGENDA_DELETE_REQUEST";
export const CATEGORIA_AGENDA_DELETE_SUCCESS = "CATEGORIA_AGENDA_DELETE_SUCCESS";
export const CATEGORIA_AGENDA_DELETE_FAIL = "CATEGORIA_AGENDA_DELETE_FAIL";

