export const CATEGORIA_PESSOA_LIST_REQUEST = "CATEGORIA_PESSOA_LIST_REQUEST";
export const CATEGORIA_PESSOA_LIST_SUCCESS = "CATEGORIA_PESSOA_LIST_SUCCESS";
export const CATEGORIA_PESSOA_LIST_FAIL = "CATEGORIA_PESSOA_LIST_FAIL";

export const CATEGORIA_PESSOA_DETAILS_REQUEST = "CATEGORIA_PESSOA_DETAILS_REQUEST";
export const CATEGORIA_PESSOA_DETAILS_SUCCESS = "CATEGORIA_PESSOA_DETAILS_SUCCESS";
export const CATEGORIA_PESSOA_DETAILS_FAIL = "CATEGORIA_PESSOA_DETAILS_FAIL";

export const CATEGORIA_PESSOA_CREATE_REQUEST = "CATEGORIA_PESSOA_CREATE_REQUEST";
export const CATEGORIA_PESSOA_CREATE_SUCCESS = "CATEGORIA_PESSOA_CREATE_SUCCESS";
export const CATEGORIA_PESSOA_CREATE_FAIL = "CATEGORIA_PESSOA_CREATE_FAIL";
export const CATEGORIA_PESSOA_CREATE_RESET = "CATEGORIA_PESSOA_CREATE_RESET";

export const CATEGORIA_PESSOA_UPDATE_REQUEST = "CATEGORIA_PESSOA_UPDATE_REQUEST";
export const CATEGORIA_PESSOA_UPDATE_SUCCESS = "CATEGORIA_PESSOA_UPDATE_SUCCESS";
export const CATEGORIA_PESSOA_UPDATE_FAIL = "CATEGORIA_PESSOA_UPDATE_FAIL";
export const CATEGORIA_PESSOA_UPDATE_RESET = "CATEGORIA_PESSOA_UPDATE_RESET";

export const CATEGORIA_PESSOA_DELETE_REQUEST = "CATEGORIA_PESSOA_DELETE_REQUEST";
export const CATEGORIA_PESSOA_DELETE_SUCCESS = "CATEGORIA_PESSOA_DELETE_SUCCESS";
export const CATEGORIA_PESSOA_DELETE_FAIL = "CATEGORIA_PESSOA_DELETE_FAIL";
