export const CEP_FETCH_REQUEST = "CEP_FETCH_REQUEST";
export const CEP_FETCH_SUCCESS = "CEP_FETCH_SUCCESS";
export const CEP_FETCH_FAIL = "CEP_FETCH_FAIL";
export const CEP_FETCH_RESET = "CEP_FETCH_RESET";
