export const ESTADO_CIVIL_LIST_REQUEST = "ESTADO_CIVIL_LIST_REQUEST";
export const ESTADO_CIVIL_LIST_SUCCESS = "ESTADO_CIVIL_LIST_SUCCESS";
export const ESTADO_CIVIL_LIST_FAIL = "ESTADO_CIVIL_LIST_FAIL";

export const ESTADO_CIVIL_DETAILS_REQUEST = "ESTADO_CIVIL_DETAILS_REQUEST";
export const ESTADO_CIVIL_DETAILS_SUCCESS = "ESTADO_CIVIL_DETAILS_SUCCESS";
export const ESTADO_CIVIL_DETAILS_FAIL = "ESTADO_CIVIL_DETAILS_FAIL";

export const ESTADO_CIVIL_CREATE_REQUEST = "ESTADO_CIVIL_CREATE_REQUEST";
export const ESTADO_CIVIL_CREATE_SUCCESS = "ESTADO_CIVIL_CREATE_SUCCESS";
export const ESTADO_CIVIL_CREATE_FAIL = "ESTADO_CIVIL_CREATE_FAIL";
export const ESTADO_CIVIL_CREATE_RESET = "ESTADO_CIVIL_CREATE_RESET";

export const ESTADO_CIVIL_UPDATE_REQUEST = "ESTADO_CIVIL_UPDATE_REQUEST";
export const ESTADO_CIVIL_UPDATE_SUCCESS = "ESTADO_CIVIL_UPDATE_SUCCESS";
export const ESTADO_CIVIL_UPDATE_FAIL = "ESTADO_CIVIL_UPDATE_FAIL";
export const ESTADO_CIVIL_UPDATE_RESET = "ESTADO_CIVIL_UPDATE_RESET";

export const ESTADO_CIVIL_DELETE_REQUEST = "ESTADO_CIVIL_DELETE_REQUEST";
export const ESTADO_CIVIL_DELETE_SUCCESS = "ESTADO_CIVIL_DELETE_SUCCESS";
export const ESTADO_CIVIL_DELETE_FAIL = "ESTADO_CIVIL_DELETE_FAIL";
