export const EVENTO_LIST_REQUEST = "EVENTO_LIST_REQUEST";
export const EVENTO_LIST_SUCCESS = "EVENTO_LIST_SUCCESS";
export const EVENTO_LIST_FAIL = "EVENTO_LIST_FAIL";

export const EVENTO_DETAILS_REQUEST = "EVENTO_DETAILS_REQUEST";
export const EVENTO_DETAILS_SUCCESS = "EVENTO_DETAILS_SUCCESS";
export const EVENTO_DETAILS_FAIL = "EVENTO_DETAILS_FAIL";

export const EVENTO_CREATE_REQUEST = "EVENTO_CREATE_REQUEST";
export const EVENTO_CREATE_SUCCESS = "EVENTO_CREATE_SUCCESS";
export const EVENTO_CREATE_FAIL = "EVENTO_CREATE_FAIL";
export const EVENTO_CREATE_RESET = "EVENTO_CREATE_RESET";

export const EVENTO_UPDATE_REQUEST = "EVENTO_UPDATE_REQUEST";
export const EVENTO_UPDATE_SUCCESS = "EVENTO_UPDATE_SUCCESS";
export const EVENTO_UPDATE_FAIL = "EVENTO_UPDATE_FAIL";
export const EVENTO_UPDATE_RESET = "EVENTO_UPDATE_RESET";

export const EVENTO_DELETE_REQUEST = "EVENTO_DELETE_REQUEST";
export const EVENTO_DELETE_SUCCESS = "EVENTO_DELETE_SUCCESS";
export const EVENTO_DELETE_FAIL = "EVENTO_DELETE_FAIL";
