export const EVENTO_AO_VIVO_LIST_REQUEST = "EVENTO_AO_VIVO_LIST_REQUEST";
export const EVENTO_AO_VIVO_LIST_SUCCESS = "EVENTO_AO_VIVO_LIST_SUCCESS";
export const EVENTO_AO_VIVO_LIST_FAIL = "EVENTO_AO_VIVO_LIST_FAIL";

export const EVENTO_AO_VIVO_DETAILS_REQUEST = "EVENTO_AO_VIVO_DETAILS_REQUEST";
export const EVENTO_AO_VIVO_DETAILS_SUCCESS = "EVENTO_AO_VIVO_DETAILS_SUCCESS";
export const EVENTO_AO_VIVO_DETAILS_FAIL = "EVENTO_AO_VIVO_DETAILS_FAIL";

export const EVENTO_AO_VIVO_CREATE_REQUEST = "EVENTO_AO_VIVO_CREATE_REQUEST";
export const EVENTO_AO_VIVO_CREATE_SUCCESS = "EVENTO_AO_VIVO_CREATE_SUCCESS";
export const EVENTO_AO_VIVO_CREATE_FAIL = "EVENTO_AO_VIVO_CREATE_FAIL";
export const EVENTO_AO_VIVO_CREATE_RESET = "EVENTO_AO_VIVO_CREATE_RESET";

export const EVENTO_AO_VIVO_UPDATE_REQUEST = "EVENTO_AO_VIVO_UPDATE_REQUEST";
export const EVENTO_AO_VIVO_UPDATE_SUCCESS = "EVENTO_AO_VIVO_UPDATE_SUCCESS";
export const EVENTO_AO_VIVO_UPDATE_FAIL = "EVENTO_AO_VIVO_UPDATE_FAIL";
export const EVENTO_AO_VIVO_UPDATE_RESET = "EVENTO_AO_VIVO_UPDATE_RESET";

export const EVENTO_AO_VIVO_DELETE_REQUEST = "EVENTO_AO_VIVO_DELETE_REQUEST";
export const EVENTO_AO_VIVO_DELETE_SUCCESS = "EVENTO_AO_VIVO_DELETE_SUCCESS";
export const EVENTO_AO_VIVO_DELETE_FAIL = "EVENTO_AO_VIVO_DELETE_FAIL";

