export const GENERO_LIST_REQUEST = "GENERO_LIST_REQUEST";
export const GENERO_LIST_SUCCESS = "GENERO_LIST_SUCCESS";
export const GENERO_LIST_FAIL = "GENERO_LIST_FAIL";

export const GENERO_DETAILS_REQUEST = "GENERO_DETAILS_REQUEST";
export const GENERO_DETAILS_SUCCESS = "GENERO_DETAILS_SUCCESS";
export const GENERO_DETAILS_FAIL = "GENERO_DETAILS_FAIL";

export const GENERO_CREATE_REQUEST = "GENERO_CREATE_REQUEST";
export const GENERO_CREATE_SUCCESS = "GENERO_CREATE_SUCCESS";
export const GENERO_CREATE_FAIL = "GENERO_CREATE_FAIL";
export const GENERO_CREATE_RESET = "GENERO_CREATE_RESET";

export const GENERO_UPDATE_REQUEST = "GENERO_UPDATE_REQUEST";
export const GENERO_UPDATE_SUCCESS = "GENERO_UPDATE_SUCCESS";
export const GENERO_UPDATE_FAIL = "GENERO_UPDATE_FAIL";
export const GENERO_UPDATE_RESET = "GENERO_UPDATE_RESET";

export const GENERO_DELETE_REQUEST = "GENERO_DELETE_REQUEST";
export const GENERO_DELETE_SUCCESS = "GENERO_DELETE_SUCCESS";
export const GENERO_DELETE_FAIL = "GENERO_DELETE_FAIL";

