export const IGREJA_LIST_REQUEST = "IGREJA_LIST_REQUEST";
export const IGREJA_LIST_SUCCESS = "IGREJA_LIST_SUCCESS";
export const IGREJA_LIST_FAIL = "IGREJA_LIST_FAIL";

export const IGREJA_DETAILS_REQUEST = "IGREJA_DETAILS_REQUEST";
export const IGREJA_DETAILS_SUCCESS = "IGREJA_DETAILS_SUCCESS";
export const IGREJA_DETAILS_FAIL = "IGREJA_DETAILS_FAIL";

export const IGREJA_CREATE_REQUEST = "IGREJA_CREATE_REQUEST";
export const IGREJA_CREATE_SUCCESS = "IGREJA_CREATE_SUCCESS";
export const IGREJA_CREATE_FAIL = "IGREJA_CREATE_FAIL";
export const IGREJA_CREATE_RESET = "IGREJA_CREATE_RESET";

export const IGREJA_UPDATE_REQUEST = "IGREJA_UPDATE_REQUEST";
export const IGREJA_UPDATE_SUCCESS = "IGREJA_UPDATE_SUCCESS";
export const IGREJA_UPDATE_FAIL = "IGREJA_UPDATE_FAIL";
export const IGREJA_UPDATE_RESET = "IGREJA_UPDATE_RESET";

export const IGREJA_DELETE_REQUEST = "IGREJA_DELETE_REQUEST";
export const IGREJA_DELETE_SUCCESS = "IGREJA_DELETE_SUCCESS";
export const IGREJA_DELETE_FAIL = "IGREJA_DELETE_FAIL";

