export const NOTICIA_LIST_REQUEST = "NOTICIA_LIST_REQUEST";
export const NOTICIA_LIST_SUCCESS = "NOTICIA_LIST_SUCCESS";
export const NOTICIA_LIST_FAIL = "NOTICIA_LIST_FAIL";

export const NOTICIA_DETAILS_REQUEST = "NOTICIA_DETAILS_REQUEST";
export const NOTICIA_DETAILS_SUCCESS = "NOTICIA_DETAILS_SUCCESS";
export const NOTICIA_DETAILS_FAIL = "NOTICIA_DETAILS_FAIL";

export const NOTICIA_CREATE_REQUEST = "NOTICIA_CREATE_REQUEST";
export const NOTICIA_CREATE_SUCCESS = "NOTICIA_CREATE_SUCCESS";
export const NOTICIA_CREATE_FAIL = "NOTICIA_CREATE_FAIL";
export const NOTICIA_CREATE_RESET = "NOTICIA_CREATE_RESET";

export const NOTICIA_UPDATE_REQUEST = "NOTICIA_UPDATE_REQUEST";
export const NOTICIA_UPDATE_SUCCESS = "NOTICIA_UPDATE_SUCCESS";
export const NOTICIA_UPDATE_FAIL = "NOTICIA_UPDATE_FAIL";
export const NOTICIA_UPDATE_RESET = "NOTICIA_UPDATE_RESET";

export const NOTICIA_DELETE_REQUEST = "NOTICIA_DELETE_REQUEST";
export const NOTICIA_DELETE_SUCCESS = "NOTICIA_DELETE_SUCCESS";
export const NOTICIA_DELETE_FAIL = "NOTICIA_DELETE_FAIL";
