export const PESSOA_LIST_REQUEST = "PESSOA_LIST_REQUEST";
export const PESSOA_LIST_SUCCESS = "PESSOA_LIST_SUCCESS";
export const PESSOA_LIST_FAIL = "PESSOA_LIST_FAIL";

export const PESSOA_DETAILS_REQUEST = "PESSOA_DETAILS_REQUEST";
export const PESSOA_DETAILS_SUCCESS = "PESSOA_DETAILS_SUCCESS";
export const PESSOA_DETAILS_FAIL = "PESSOA_DETAILS_FAIL";

export const PESSOA_CREATE_REQUEST = "PESSOA_CREATE_REQUEST";
export const PESSOA_CREATE_SUCCESS = "PESSOA_CREATE_SUCCESS";
export const PESSOA_CREATE_FAIL = "PESSOA_CREATE_FAIL";
export const PESSOA_CREATE_RESET = "PESSOA_CREATE_RESET";

export const PESSOA_UPDATE_REQUEST = "PESSOA_UPDATE_REQUEST";
export const PESSOA_UPDATE_SUCCESS = "PESSOA_UPDATE_SUCCESS";
export const PESSOA_UPDATE_FAIL = "PESSOA_UPDATE_FAIL";
export const PESSOA_UPDATE_RESET = "PESSOA_UPDATE_RESET";

export const PESSOA_DELETE_REQUEST = "PESSOA_DELETE_REQUEST";
export const PESSOA_DELETE_SUCCESS = "PESSOA_DELETE_SUCCESS";
export const PESSOA_DELETE_FAIL = "PESSOA_DELETE_FAIL";

