export const PROFISSAO_LIST_REQUEST = 'PROFISSAO_LIST_REQUEST';
export const PROFISSAO_LIST_SUCCESS = 'PROFISSAO_LIST_SUCCESS';
export const PROFISSAO_LIST_FAIL = 'PROFISSAO_LIST_FAIL';

export const PROFISSAO_DETAILS_REQUEST = 'PROFISSAO_DETAILS_REQUEST';
export const PROFISSAO_DETAILS_SUCCESS = 'PROFISSAO_DETAILS_SUCCESS';
export const PROFISSAO_DETAILS_FAIL = 'PROFISSAO_DETAILS_FAIL';

export const PROFISSAO_CREATE_REQUEST = 'PROFISSAO_CREATE_REQUEST';
export const PROFISSAO_CREATE_SUCCESS = 'PROFISSAO_CREATE_SUCCESS';
export const PROFISSAO_CREATE_FAIL = 'PROFISSAO_CREATE_FAIL';
export const PROFISSAO_CREATE_RESET = 'PROFISSAO_CREATE_RESET';

export const PROFISSAO_UPDATE_REQUEST = 'PROFISSAO_UPDATE_REQUEST';
export const PROFISSAO_UPDATE_SUCCESS = 'PROFISSAO_UPDATE_SUCCESS';
export const PROFISSAO_UPDATE_FAIL = 'PROFISSAO_UPDATE_FAIL';
export const PROFISSAO_UPDATE_RESET = 'PROFISSAO_UPDATE_RESET';

export const PROFISSAO_DELETE_REQUEST = 'PROFISSAO_DELETE_REQUEST';
export const PROFISSAO_DELETE_SUCCESS = 'PROFISSAO_DELETE_SUCCESS';
export const PROFISSAO_DELETE_FAIL = 'PROFISSAO_DELETE_FAIL';
