export const VERSICULO_LIST_REQUEST = 'VERSICULO_LIST_REQUEST';
export const VERSICULO_LIST_SUCCESS = 'VERSICULO_LIST_SUCCESS';
export const VERSICULO_LIST_FAIL = 'VERSICULO_LIST_FAIL';

export const VERSICULO_DETAILS_REQUEST = 'VERSICULO_DETAILS_REQUEST';
export const VERSICULO_DETAILS_SUCCESS = 'VERSICULO_DETAILS_SUCCESS';
export const VERSICULO_DETAILS_FAIL = 'VERSICULO_DETAILS_FAIL';

export const VERSICULO_CREATE_REQUEST = 'VERSICULO_CREATE_REQUEST';
export const VERSICULO_CREATE_SUCCESS = 'VERSICULO_CREATE_SUCCESS';
export const VERSICULO_CREATE_FAIL = 'VERSICULO_CREATE_FAIL';
export const VERSICULO_CREATE_RESET = 'VERSICULO_CREATE_RESET';

export const VERSICULO_UPDATE_REQUEST = 'VERSICULO_UPDATE_REQUEST';
export const VERSICULO_UPDATE_SUCCESS = 'VERSICULO_UPDATE_SUCCESS';
export const VERSICULO_UPDATE_FAIL = 'VERSICULO_UPDATE_FAIL';
export const VERSICULO_UPDATE_RESET = 'VERSICULO_UPDATE_RESET';

export const VERSICULO_DELETE_REQUEST = 'VERSICULO_DELETE_REQUEST';
export const VERSICULO_DELETE_SUCCESS = 'VERSICULO_DELETE_SUCCESS';
export const VERSICULO_DELETE_FAIL = 'VERSICULO_DELETE_FAIL';